GET http://localhost:8001/users
###
POST http://localhost:8001/users
Content-Type: application/json

{
  "firstname":"Sayar",
  "lastname":"Bhattacharyya",
  "age":19,
  "email":"sayar@gmail.com",
  "password":"hello"
}
